### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by nuryagdym** [kasteckis/symfony-docker-compose#1]
Hello, 
I download your code and trying to get it running. Already spent 3 hours still it does not work. I am trying to run it on my Windows 10 PC. 
Build was successful, all your code was copy pasted. 
![image](https://user-images.githubusercontent.com/26792980/95681531-fb37fa00-0be8-11eb-8d25-06b34c0cb540.png)

I can't reach neither Apache server (192.168.2.2) nor phpMyAdmin (192.168.2.4)

I am getting **This site can’t be reached192.168.3.2 took too long to respond.** error. Do you know what can cause it?

**Comment by kasteckis** [comment]
@nuryagdym, I haven't tested this on Windows. Docker sometimes work differently on different OS's.

I would suggest you to try to visit `0.0.0.0:80` on your browser.

Also try to visit `0.0.0.0:8183` to see maybe phpmyadmin works.

Let me know if this helped.

**Comment by nuryagdym** [comment]
Finally, I was able to solve the issue. 
The first problem is the port configuration, `"80:8080"`, of the **web** container.
It should be **"80:80"** because apache serves on 80 port not 8080.
The second problem is, with `DATABASE_URL=mysql://root:symfony_password@192.168.2.3:3306/project?serverVersion=5.7` this configuration in `.env` web container is trying to connect DB in the same host (192.168.2.2):
![image](https://user-images.githubusercontent.com/26792980/96353315-698e2800-10d3-11eb-8401-167c41c93d83.png)

And final problem is, I can connect to this containers only via `localhost`. 192.168.2.0 network address seems the address containers use internally between each other

**Comment by kasteckis** [comment]
Thanks for letting me know. 

1st problem - Since I've been testing this only on Ubuntu 20.04, it worked with previous mappings, but it also works with yours, so I changed them.

2nd problem - by default it should be `DATABASE_URL=mysql://root:@192.168.2.3:3306/project`

3rd problem - On Ubuntu 20.04 I can easily allocate 192.168.2.0/24 without any problems, haven't tested on Windows, you can always change that.
