### ISSUE TITLE
fails on windows 10

### ISSUE THREAD

**Issue by logosur** [kasteckis/symfony-docker-compose#2]
project_develop_init doesn't gets up. To fix it you must convert CR to CRLF in develop_init.sh
even in docker_compose.yml command must be:
command: "sh /usr/local/bin/develop_init"
or it throws "develop_init not found"

phpmyadmin shows login page but can't connect with error:
mysqli::real_connect(): (HY000/2002): No such file or directory

**Comment by kasteckis** [comment]
This project was made for Ubuntu (works also on MacOS).

To convert CR to CLRF check out this - https://stackoverflow.com/questions/19912941/convert-all-cr-to-crlf-in-text-file-using-cmd

File which is `.docker/develop_init.sh` has extension `.sh` which indicates that this is a shell script, strange that you need to remove that extension.

Can't tell anything about mysql error, need more information.
